# Generated by Django 4.0.5 on 2022-06-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('blog', '0006_blogpagegalleryimage_blogindexgalleryimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogIndexGalleryImage',
            new_name='BlogIndexPageGalleryImage',
        ),
    ]
